baseURL: "https://icysamon.jp/"
title: icysamon
copyright: "© [icysamon](https://icysamon.jp/)"
theme: [PaperMod]
languageCode: ja
publishDir : docs

permalinks:
    post: /post/:slug/
    page: /:slug/

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

params:
  ShowPostNavLinks: false
  assets:
    disableFingerprinting: true
  profileMode:
    enabled: true
    title: # optional default will be site title
    subtitle: "電子工作｜ゲーム開発｜作曲"
    imageUrl: "https://image.icysamon.jp/avatar/000.png" # optional
    imageTitle: # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size
    buttons:
      - name: 作品集
        url: "/post/"
      - name: Blog
        url: "https://blog.icysamon.jp/"

  socialIcons: # optional
    - name: "bluesky"
      url: "https://bsky.app/profile/icysamon.jp"
    - name: "github"
      url: "https://github.com/icysamon"
    - name: "applemusic"
      url: "https://music.apple.com/jp/artist/icysamon/1808762015"
    - name: "spotify"
      url: "https://open.spotify.com/intl-ja/artist/7tk5ryKLzZdGvABO1H0LCx"
    - name: "email"
      url: "mailto:mail@icysamon.jp"

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 40