services:
  web:
    image: node:22.16-alpine
    container_name: hp-dev
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: 
    name: hp_node_modules